// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTE-Kw1L9B0WWDtX3j9kVJClqGssbdE5M',
    appId: '1:830376997558:web:865484f24b99301cad2c17',
    messagingSenderId: '830376997558',
    projectId: 'app-academic-connect',
    authDomain: 'app-academic-connect.firebaseapp.com',
    storageBucket: 'app-academic-connect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqfBldOVLJIetlovGJTi-RAR0hh1L6Is',
    appId: '1:830376997558:android:b63d2e87f2bfc1d9ad2c17',
    messagingSenderId: '830376997558',
    projectId: 'app-academic-connect',
    storageBucket: 'app-academic-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2KNBOByCZo_e-AY1MCHj2QkkvoqVloQ',
    appId: '1:830376997558:ios:33168cb5897634e9ad2c17',
    messagingSenderId: '830376997558',
    projectId: 'app-academic-connect',
    storageBucket: 'app-academic-connect.firebasestorage.app',
    iosClientId: '830376997558-ruaram7cg93ol3l96hfeu7rddpkn9vq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddmProjetoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2KNBOByCZo_e-AY1MCHj2QkkvoqVloQ',
    appId: '1:830376997558:ios:33168cb5897634e9ad2c17',
    messagingSenderId: '830376997558',
    projectId: 'app-academic-connect',
    storageBucket: 'app-academic-connect.firebasestorage.app',
    iosClientId: '830376997558-ruaram7cg93ol3l96hfeu7rddpkn9vq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddmProjetoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTE-Kw1L9B0WWDtX3j9kVJClqGssbdE5M',
    appId: '1:830376997558:web:eb5b729f82503a22ad2c17',
    messagingSenderId: '830376997558',
    projectId: 'app-academic-connect',
    authDomain: 'app-academic-connect.firebaseapp.com',
    storageBucket: 'app-academic-connect.firebasestorage.app',
  );
}
